engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    config:
      ignore-undeclared: true
      dead-code-detection: true
exclude_paths:
- test/
- vendor/
