dist: trusty
language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
services:
  - mysql
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script: 
  - composer install
  - mysql -u root -e 'create database autowp_test;'
  - mysql -u root < test/_files/dump.sql
  - mysql -u root -e 'GRANT ALL PRIVILEGES ON autowp_test.* TO autowp_test@localhost IDENTIFIED BY "test";'

script:
- ./vendor/bin/phpunit --coverage-clover ./test/logs/clover.xml
 
after_script:
- ./vendor/bin/coveralls -v
- ./vendor/bin/test-reporter -v --coverage-report=./test/logs/clover.xml
