dist: trusty
language: php
php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
services:
- mysql
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  sonarcloud:
    organization: autowp-github
    token:
      secure: 4AyMDymj/ULC8Pc4tZ10i44e1V/sBQAsNBJnuDh8IBTXZtSNdjtnjvSON4vRnTTDBztEb8j5xTQSx/UAfJPPQTiyWKRQC3XG/bmfe+HYHZPVhGGjWWAR/QD1bQAVKLl23ErVtuMt2PjRZ/vfahTYiWgplcl4Yz5uAI9caKly94Yuukg6cuk3otwchdAIOOZKFRLzZOYsd5vg1Ee+sqxHH0He1UvRkLx30x9C5zbbMa6mpT1v4g8ZsLv+fjZVnz8dwjNIpRebtN4Q8SOJug4He25NDTObsY9ZIR35b8caGyirElJ9s+b+UTOrsKPz0ovsmIVDBIFVdwI5Cm28Xudx/GL1aoXOSnuYJRr8dZIAmFu/EZnMzyeNwFOry7gs8xpXvU3HmolTeyvSZpz/wQVB/I+ngRZkg7Ypvpo0XH8a4qDDANYFj9ArP2gkDD/L4QiA/a/IlhUS5YBdjxm2yzUM0RLWY7Ah/nLOzpdnb7c8YXBOJ5I413YXJWAhihUnDqXZR0ebBuYaj6Z56019LHlZpeZqq6jW78+tG/ybGh4JhDOAsbEEVYPqKm7zy/EiBcGxD/jL+rrd2HJKt5L7ROPLBTvEeOMZTo/5f+xJmpx6ZP4T9VWi1p5Q1jBO5xqX0izgL73TJxO8WlAIg60MFT5nwnscL3gYMpWll/KUjgsit0Y=
before_script:
- composer install || travis_terminate 1;
- mysql -u root -e 'create database autowp_test;' || travis_terminate 1;
- mysql -u root < test/_files/dump.sql || travis_terminate 1;
- mysql -u root -e 'GRANT ALL PRIVILEGES ON autowp_test.* TO autowp_test@localhost
  IDENTIFIED BY "test";' || travis_terminate 1;
script:
- "./vendor/bin/phpunit --coverage-clover ./test/logs/clover.xml"
- sonar-scanner || travis_terminate 1;
after_script:
- "./vendor/bin/coveralls -v"
- "./vendor/bin/test-reporter -v --coverage-report=./test/logs/clover.xml"

